= Impact Analysis Of 8 Remaining Risks In 7 Categories
:fn-risk-findings: footnote:riskfinding[Risk finding paragraphs are clickable and link to the corresponding chapter.]
The most prevalent impacts of the *8 remaining risks* (distributed over *7 risk categories*) are (taking the severity ratings into account and using the highest for each category)!{fn-risk-findings}

<<missing-authentication,[.ElevatedRisk]#Elevated: *Missing Authentication*: 1 Remaining Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access or modify sensitive data in an unauthenticated way.

<<missing-hardening,[.ElevatedRisk]#Elevated: *Missing Hardening*: 1 Remaining Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk remains unmitigated, attackers might be able to easier attack high-value targets.

<<server-side-request-forgery,[.ElevatedRisk]#Elevated: *Server-Side Request Forgery (SSRF)*: 1 Remaining Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access sensitive services or files of network-reachable components by modifying outgoing calls of affected components.

<<unencrypted-communication,[.ElevatedRisk]#Elevated: *Unencrypted Communication*: 2 Remaining Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, network attackers might be able to to eavesdrop on unencrypted sensitive data sent between components.

<<missing-build-infrastructure,[.MediumRisk]#Medium: *Missing Build Infrastructure*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to exploit risks unseen in this threat model due to critical build infrastructure components missing in the model.

<<missing-vault,[.MediumRisk]#Medium: *Missing Vault (Secret Storage)*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to easier steal config secrets (like credentials, private keys, client certificates, etc.) once a vulnerability to access files is present and exploited.

<<missing-waf,[.MediumRisk]#Medium: *Missing Web Application Firewall (WAF)*: 1 Remaining Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to apply standard attack pattern tests at great speed without any filtering.

