= STRIDE Classification of Identified Risks
:fn-risk-findings: footnote:riskfinding[Risk finding paragraphs are clickable and link to the corresponding chapter.]

This chapter clusters and classifies the risks by STRIDE categories: In total *10 potential risks* have been identified during the threat modeling process of which *0 in the Spoofing* category, *4 in the Tampering* category, *0 in the Repudiation* category, *4 in the Information Disclosure* category, *0 in the Denial of Service* category, and *2 in the Elevation of Privilege* category.{fn-risk-findings}

== Spoofing
No risk identified.

== Tampering
<<missing-hardening,[.ElevatedRisk]#Elevated: *Missing Hardening*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk remains unmitigated, attackers might be able to easier attack high-value targets.

<<untrusted-deserialization,[.ElevatedRisk]#Elevated: *Untrusted Deserialization*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Very High_ impact.#>>::
If this risk is unmitigated, attackers might be able to execute code on target systems by exploiting untrusted deserialization endpoints.

<<missing-build-infrastructure,[.MediumRisk]#Medium: *Missing Build Infrastructure*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to exploit risks unseen in this threat model due to critical build infrastructure components missing in the model.

<<missing-waf,[.MediumRisk]#Medium: *Missing Web Application Firewall (WAF)*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to apply standard attack pattern tests at great speed without any filtering.


== Repudiation
No risk identified.

== Information Disclosure
<<server-side-request-forgery,[.ElevatedRisk]#Elevated: *Server-Side Request Forgery (SSRF)*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access sensitive services or files of network-reachable components by modifying outgoing calls of affected components.

<<unencrypted-communication,[.ElevatedRisk]#Elevated: *Unencrypted Communication*: 2/2 unmitigated Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, network attackers might be able to to eavesdrop on unencrypted sensitive data sent between components.

<<missing-vault,[.MediumRisk]#Medium: *Missing Vault (Secret Storage)*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to easier steal config secrets (like credentials, private keys, client certificates, etc.) once a vulnerability to access files is present and exploited.


== Denial of Service
No risk identified.

== Elevation of Privilege
<<missing-authentication,[.ElevatedRisk]#Elevated: *Missing Authentication*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access or modify sensitive data in an unauthenticated way.

<<missing-authentication-second-factor,[.MediumRisk]#Medium: *Missing Two-Factor Authentication (2FA)*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access or modify highly sensitive data without strong authentication.


