= Assignment by Function
:fn-risk-findings: footnote:riskfinding[Risk finding paragraphs are clickable and link to the corresponding chapter.]

This chapter clusters and assigns the risks by functions which are most likely able to check and mitigate them: In total *10 potential risks* have been identified during the threat modeling process of which *1 should be checked by Business Side*, *4 should be checked by Architecture*, *1 should be checked by Development*, and *4 should be checked by Operations*.{fn-risk-findings}

== Business Side
<<missing-authentication-second-factor,Medium: *Missing Two-Factor Authentication (2FA)*: 1 mitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.>>::
If this risk is unmitigated, attackers might be able to access or modify highly sensitive data without strong authentication.


== Architecture
<<missing-authentication,[.ElevatedRisk]#Elevated: *Missing Authentication*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access or modify sensitive data in an unauthenticated way.

<<untrusted-deserialization,Elevated: *Untrusted Deserialization*: 1 mitigated Risk - Exploitation likelihood is _Likely_ with _Very High_ impact.>>::
If this risk is unmitigated, attackers might be able to execute code on target systems by exploiting untrusted deserialization endpoints.

<<missing-build-infrastructure,[.MediumRisk]#Medium: *Missing Build Infrastructure*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to exploit risks unseen in this threat model due to critical build infrastructure components missing in the model.

<<missing-vault,[.MediumRisk]#Medium: *Missing Vault (Secret Storage)*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to easier steal config secrets (like credentials, private keys, client certificates, etc.) once a vulnerability to access files is present and exploited.


== Development
<<server-side-request-forgery,[.ElevatedRisk]#Elevated: *Server-Side Request Forgery (SSRF)*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to access sensitive services or files of network-reachable components by modifying outgoing calls of affected components.


== Operations
<<missing-hardening,[.ElevatedRisk]#Elevated: *Missing Hardening*: 1/1 unmitigated Risk - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk remains unmitigated, attackers might be able to easier attack high-value targets.

<<unencrypted-communication,[.ElevatedRisk]#Elevated: *Unencrypted Communication*: 2/2 unmitigated Risks - Exploitation likelihood is _Likely_ with _Medium_ impact.#>>::
If this risk is unmitigated, network attackers might be able to to eavesdrop on unencrypted sensitive data sent between components.

<<missing-waf,[.MediumRisk]#Medium: *Missing Web Application Firewall (WAF)*: 1/1 unmitigated Risk - Exploitation likelihood is _Unlikely_ with _Medium_ impact.#>>::
If this risk is unmitigated, attackers might be able to apply standard attack pattern tests at great speed without any filtering.


